---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db-data
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
