---
kind: Secret
apiVersion: v1
metadata:
  name: postgresql-db-credentials
  namespace: {{ .Values.global.namespace }}
stringData:
  username: testuser
  password: testpassword
  database: keycloak
type: Opaque
