---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:15
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-credentials
                  key: database
            - name: PGDATA
              value: /data/pgdata
          volumeMounts:
            - mountPath: /data
              name: data-volume
      volumes:
        - name: data-volume
          # emptyDir: {}
          persistentVolumeClaim:
            claimName: postgresql-db-data
