---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hub-setup
  name: hub-setup
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  project: default
  source:
    repoURL: https://github.com/alvarolop/workshop-gitops-infra-deploy.git
    targetRevision: main
    path: 02-hub-setup
    helm:
      values: |
        global:
          domain: $CLUSTER_DOMAIN
          # sno:
          #   "01":
          #     username: kubeadmin
          #     password: $password
          #   "02":
          #     username: kubeadmin
          #     password: $password
          #   "03":
          #     username: kubeadmin
          #     password: $password
          #   # ...
          # Insert here output of ocp4-print-kubeadmin.sh

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
