---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hashicorp-vault-server
  name: hashicorp-vault-server
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.29.1
    chart: vault
    helm:
      values: |
        global:
          openshift: true
        injector:
          enabled: false
        server:
          dev:
            enabled: true
          # standalone:
          #   enabled: true
          # https://developer.hashicorp.com/vault/docs/platform/k8s/helm/configuration#datastorage
          # dataStorage:
          #   enabled: true
          #   size: 20Gi
          route:
            enabled: true
            host: ''
            tls: 
              termination: edge
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
