# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  namespace: keycloak
  # sandbox3037.opentlc.com
  clusterDomain: $BASE_DOMAIN

numberOfClusters: 2
