---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
spec:
  channel: stable-v26.0
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
