---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - argocd-sa

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: htpass-secret
    files:
      - htpasswd=htpasswd

namespace: openshift-config