{{- if $.Values.global.render }}
{{- range $key, $val := $.Values.global.sno }}
---
kind: Secret
apiVersion: v1
metadata:
  name: cluster-api.sno-{{ $key }}.{{ $.Values.global.domain }}
  namespace:  {{ $.Values.global.namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
  {{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  {{- end }}      
type: Opaque
stringData:
  name: sno-{{ $key }}
  project: project-sno-{{ $key }}
  server: 'https://api.sno-{{ $key }}.{{ $.Values.global.domain }}:6443'
  config: |
    {
  {{- if $val.token }}
      "bearerToken": "{{ $val.token }}",
  {{- else }}
      "username": "{{ $val.username }}",
      "password": "{{ $val.password }}",
  {{- end }}
      "tlsClientConfig": {
        "insecure": true
      }
    }
{{- end }}
{{- end }}  