{{- if $.Values.global.render -}}
---
kind: ArgoCD
apiVersion: argoproj.io/v1beta1
metadata:
  name: openshift-gitops
  namespace: {{ $.Values.global.namespace }}
  {{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  {{- end }}    
spec:
  applicationSet:
    logLevel: info
  resourceTrackingMethod: annotation+label
  controller:
    sharding:
      enabled: true
      replicas: {{ $.Values.global.sharding }}   
    logLevel: debug
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  rbac:
    defaultPolicy: ''
    policy: |
      {{- range $key, $val := $.Values.global.sno }}
      p, role:admin-sno-{{ $key }}, applications, *, project-sno-{{ $key }}/*, allow 
      p, role:admin-sno-{{ $key }}, clusters, get, project-sno-{{ $key }}/*, allow
      p, role:admin-sno-{{ $key }}, repositories, *, project-sno-{{ $key }}/*, allow
      g, admin-sno-{{ $key }}, role:admin-sno-{{ $key }}
      {{- end }}
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
    scopes: '[groups]'
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun        
  server:
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
{{- end -}}  